In [2]:
import numpy as np
import scipy

# Eigen Value and Singular Values

In [3]:
W= np.array([[1,3,2,4,6],[3,2,7,8,7],[2,7,3,7,8],[4,8,7,4,9],[6,7,8,9,5]])
print(W)

[[1 3 2 4 6]
 [3 2 7 8 7]
 [2 7 3 7 8]
 [4 8 7 4 9]
 [6 7 8 9 5]]


In [4]:
eigen_value = np.linalg.eigvals(W)
print(eigen_value)

[28.76788357  0.33568739 -5.94300937 -4.66313837 -3.49742322]


In [5]:
W_Transpose=W.T
A=np.multiply(W,W_Transpose)
eigen_value_A=np.linalg.eigvals(A)
print(eigen_value_A)
singular_value=scipy.sqrt(eigen_value_A)
print(singular_value)

[199.9057806    4.44297896 -71.79533059 -43.52551197 -34.02791699]
[14.13880407+0.j          2.10783751+0.j          0.        +8.47321253j
  0.        +6.59738675j  0.        +5.83334527j]


# L2 Norm

In [6]:
W= np.array([[1,3,2,4,6],[3,2,7,8,7],[2,7,3,7,8],[4,8,7,4,9],[6,7,8,9,5]])
y0=np.array([1,0,0,0,0])
b=np.array([0,1,0,0,0])
#1=np.add((W*y0),b)
#1=W.T*y0+b
y1=np.dot(W.T,y0)+b
print(y1)
L2=np.linalg.norm(y1)
print(L2)

[1 4 2 4 6]
8.54400374531753


In [9]:
#y2=W*y1+b
y2=np.dot(W.T,y1)+b
L2_y2=np.linalg.norm(y2)
L2_y0=np.linalg.norm(y0)
print(L2_y2/L2_y0)

234.86379031259798
