In [1]:
import numpy as np
import scipy

# Eigen Value and Singular Values

In [5]:
W_array=np.array([[1,3,2,4,6],[3,2,7,8,7],[2,7,3,7,8],[4,8,7,4,9],[6,7,8,9,5]])

In [6]:
W= np.mat([[1,3,2,4,6],[3,2,7,8,7],[2,7,3,7,8],[4,8,7,4,9],[6,7,8,9,5]])
print(W)

[[1 3 2 4 6]
 [3 2 7 8 7]
 [2 7 3 7 8]
 [4 8 7 4 9]
 [6 7 8 9 5]]


In [7]:
eigen_value = np.linalg.eigvals(W)
print(eigen_value)
print(np.linalg.eigvals(W_array))

[28.76788357  0.33568739 -5.94300937 -4.66313837 -3.49742322]
[28.76788357  0.33568739 -5.94300937 -4.66313837 -3.49742322]


In [9]:
W= np.mat([[1,3,2,4,6],[3,2,7,8,7],[2,7,3,7,8],[4,8,7,4,9],[6,7,8,9,5]])
W2=W*W
e_W2=np.linalg.eigvals(W2)
print(scipy.sqrt(e_W2))
W2_array=np.dot(W_array,W_array)
e_W2_array=np.linalg.eigvals(W2_array)
print(scipy.sqrt(e_W2_array))

[28.76788357  0.33568739  5.94300937  4.66313837  3.49742322]
[28.76788357  0.33568739  5.94300937  4.66313837  3.49742322]


In [12]:
W_Transpose=W.T
A=W*W
eigen_value_A=np.linalg.eigvals(A)
print(eigen_value_A)
singular_value=scipy.sqrt(eigen_value_A)
print(singular_value)

[8.27591125e+02 1.12686025e-01 3.53193604e+01 2.17448594e+01
 1.22319692e+01]
[28.76788357  0.33568739  5.94300937  4.66313837  3.49742322]


# L2 Norm

In [14]:
W= np.array([[1,3,2,4,6],[3,2,7,8,7],[2,7,3,7,8],[4,8,7,4,9],[6,7,8,9,5]])
y0=np.array([1,0,0,0,0])
b=np.array([0,1,0,0,0])
y1=np.dot(W.T,y0)+b
print(y1)
L2=np.linalg.norm(y1)
print(L2)

[1 4 2 4 6]
8.54400374531753


In [15]:
#y2=W*y1+b
y2=np.dot(W.T,y1)+b
L2_y2=np.linalg.norm(y2)
L2_y0=np.linalg.norm(y0)
print(L2_y2/L2_y0)

234.86379031259798
